services:
- type: web
  name: Notty-Terminal
  runtime: static
  repo: https://github.com/NimrodTheDev/Notty-Terminal
  buildCommand: npm run build
  staticPublishPath: dist
  rootDir: ./my-react-app

- type: web
  name: solana-market-place-backend
  runtime: python
  repo: https://github.com/NimrodTheDev/Notty-Terminal
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: daphne -b 0.0.0.0 -p 8000 core.asgi:application
  rootDir: backend
version: "1"
